# Generated by Django 2.1.7 on 2019-03-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produkte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=50)),
                ('pershkrimi', models.CharField(max_length=500)),
                ('cmimi', models.IntegerField()),
                ('foto', models.CharField(max_length=500)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produktet.Kategorite')),
            ],
        ),
    ]
